
title: My Resume
url: 'https://garvit.in'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Garvit Khatri
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: me@garvit.in
website: garvit.in #do not add http://
linkedin: garvitdelhi
github: garvitdelhi
twitter: '@garvitdelhi'


# Tracker
analytics: UA-56536075-2
#Update all the sections by editing the files inside _includes folder.
